default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("LISTFY_DATABASE_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("LISTFY_DATABASE_PASSWORD") { 'postgres' } %>
  host: <%= ENV.fetch("LISTFY_DATABASE_HOST") { '127.0.0.1' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: sqlite3
  database: db/listify_dev.sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  adapter: sqlite3
  database: db/listify_test.sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default
  database: listify_prod
  username: <%= ENV.fetch("LISTFY_DATABASE_USERNAME") { 'postgres' } %>
  password: <%= ENV['LISTFY_DATABASE_PASSWORD'] %>
